apiVersion: v1
kind: Namespace
metadata:
  name: prod-core
  labels:
    opticloud.io/environment: production
    opticloud.io/network-domain: core
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ai
  labels:
    opticloud.io/environment: production
    opticloud.io/network-domain: ai
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-data
  labels:
    opticloud.io/environment: production
    opticloud.io/network-domain: data
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
